---
version: 0.1.5
commit: ":bookmark: chore: bump to version %.%.%"
files:
  README.md:
  - saku (作) v%.%.%
  - https://github.com/kt3k/saku/releases/tag/v%.%.%
  pkg/saku/const.go: "%.%.%"
  saku.md:
  - "./update_saku.sh %.%.%"
